// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqyT9tCQwxliM84UYKZt7MoZZgJGT-FYw',
    appId: '1:129730119955:web:7788d42d22ce79485d32e6',
    messagingSenderId: '129730119955',
    projectId: 'flutter-lab-8ba48',
    authDomain: 'flutter-lab-8ba48.firebaseapp.com',
    storageBucket: 'flutter-lab-8ba48.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS627t1NnFepHgs4Yv-bxYtn9BeO9MixY',
    appId: '1:129730119955:android:307e4fc3555054d95d32e6',
    messagingSenderId: '129730119955',
    projectId: 'flutter-lab-8ba48',
    storageBucket: 'flutter-lab-8ba48.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqyT9tCQwxliM84UYKZt7MoZZgJGT-FYw',
    appId: '1:129730119955:web:579b9c65d658da805d32e6',
    messagingSenderId: '129730119955',
    projectId: 'flutter-lab-8ba48',
    authDomain: 'flutter-lab-8ba48.firebaseapp.com',
    storageBucket: 'flutter-lab-8ba48.firebasestorage.app',
  );
}
